name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs automatically every day at midnight (UTC)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snake.svg
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "generate snake.svg"
          add: "assets/snake.svg"
      - name: Pull latest changes from main
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git pull origin main --rebase
      - name: Push changes to main
        run: git push origin main
